### ISSUE TITLE
Icons missing in some www offline pages

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#1186]
## Expected Behavior
Icons do not load at http://ocw-content-offline-live-qa.s3.amazonaws.com/page/2.html (see "Search" in header)

## Current Behavior
Icons should load 

## Steps to Reproduce
Visit http://ocw-content-offline-live-qa.s3.amazonaws.com/page/3.html

## Possible Solution
Unsure, but could be same root cause as https://github.com/mitodl/ocw-hugo-themes/issues/1169. @HussainTaj-arbisoft mentioned a possible bug in `path-to-root` shortcode.

**Comment by HussainTaj-arbisoft** [comment]
In https://github.com/mitodl/ocw-hugo-themes/issues/1169 `path_to_root` was receiving incorrect input. Forwarding the correct context to `resource_url` partial fixed that problem.

The equivalent partial here would be `webpack_url`. Though it looks correct to me at first glance. For example, the icons on [this](http://ocw-content-offline-live-qa.s3.amazonaws.com/courses/5-36-biochemistry-laboratory-spring-2009/pages/image-gallery/index.html#nanogallery/9c84a233-40cf-834c-b76f-84e114f60a02_nanogallery2/0/1) nested page work just fine. You see the correct imports in this page's source
```css
@font-face {
    src: local('Material Icons'),
      local('MaterialIcons-Regular'),
      url(../../static_shared/fonts/MaterialIcons-Regular.woff2) format('woff2'),
      url(../../static_shared/fonts/MaterialIcons-Regular.woff) format('woff'),
      url(../../static_shared/fonts/MaterialIcons-Regular.ttf) format('truetype');
  }
```

So far, the issue seems to be limited to the paginated index. The page http://ocw-content-offline-live-qa.s3.amazonaws.com/page/2.html

has code
```css
@font-face {
      url(./static_shared/fonts/MaterialIcons-Regular.woff2) format('woff2'),
  }
```
when it should be
```css
@font-face {
      url(../static_shared/fonts/MaterialIcons-Regular.woff2) format('woff2'),
  }
```
